Provide error checking for invalid names
If a valid cubename cannot be provided send an error message to STDERR
and return an error code of 1.

Signed-off-by: Rob Woolley <rob.woolley@windriver.com>

diff --git a/sbin/cubename b/sbin/cubename
--- a/sbin/cubename
+++ b/sbin/cubename
@@ -116,7 +116,19 @@ function extract_container_name
 	esac
     fi
 
-    echo ${output}
+
+    if [ -n "${output}" ]; then
+        echo ${output}
+        return 0
+    else
+        return 1
+    fi
 }
 
 extract_container_name $1
+if [ $? -eq 0 ] ; then
+    exit 0
+else
+    echo "ERROR: Could not determine container name" >&2
+    exit 1
+fi
