cubeit: move config file sourcing above first use
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/sbin/cubeit b/sbin/cubeit
--- a/sbin/cubeit
+++ b/sbin/cubeit
@@ -168,6 +168,15 @@ if [ "$TARGET_TYPE" = "block" ]; then
     USBSTORAGE_DEVICE=/sys/block/$(basename "$target")
 fi
 
+
+## Load functions file
+if ! [ -e $FUNCTIONS_FILE ]
+then
+	echo "ERROR: Could not find function definitions (${FUNCTIONS_FILE})"
+	exit 1
+fi
+source $FUNCTIONS_FILE
+
 ## Load configuration file(s)
 if [ -z ${CONFIG_FILES} ]; then
     echo "ERROR: no configuration was provided via --config"
@@ -220,14 +229,6 @@ INSTALLER_TARGET_SBIN_DIR="${INSTALLER_TARGET_DIR}/sbin"
 INSTALLER_TARGET_CONFIG_DIR="${INSTALLER_TARGET_DIR}/config"
 INSTALLER_TARGET_FILES_DIR="${INSTALLER_TARGET_DIR}/files"
 INSTALLER_TARGET_IMAGES_DIR="${INSTALLER_TARGET_DIR}/images"
-
-## Load functions file
-if ! [ -e $FUNCTIONS_FILE ]
-then
-	echo "ERROR: Could not find function definitions (${FUNCTIONS_FILE})"
-	exit 1
-fi
-source $FUNCTIONS_FILE
 
 # find board specific function files, and make them locally available
 for d in ${CONFIG_DIRS} $BASEDIR; do
