overc-installer:enable overlayfs for containers to reduce footprint
Many file can share among containers & essential rootfs. We can create
overlayfs mount entry in fstab of essential rootfs to re-use shared file
in containers.

To enable overlayfs for container, user need specify directory using file
from other rootfs with following parameter in $HDINSTALL_CONTAINERS:

mergepath=/dir1,[essential,[container1,]...];/dir2,[essential,[container1,]...]

When overc-installer building image:
1.It extract all containers rootfs into /tmp before installing
containers.

2.When installing containers, installer parse 'mergepath'. For user
specified directory, compare content with same directory from other
containers or essential rootfs. Then remove duplicate file to generate
final image.

3.After installing containers, add one overlayfs mount entry in fstab of
essential rootfs.

Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/installers/cubeit-installer b/installers/cubeit-installer
--- a/installers/cubeit-installer
+++ b/installers/cubeit-installer
@@ -19,6 +19,7 @@ CONTAINERSDIR="${BASEDIR}/../images/containers"
 PACKAGESDIR="${BASEDIR}/../packages"
 PUPPETDIR="${BASEDIR}/../files/puppet"
 SBINDIR="${BASEDIR}/../sbin"
+export SBINDIR
 if [ -z "${CONFIG_DIRS}" ] ; then
     CONFIG_DIRS="${BASEDIR}/../config $HOME/.overc/"
 fi
@@ -598,6 +599,31 @@ if [ -n "${HDINSTALL_CONTAINERS}" ]; then
 	fi
     done
 
+
+    CNRECORD=`mktemp /tmp/hdcontainerXXXXX`
+    export CNRECORD
+
+    for c in `strip_properties ${HDINSTALL_CONTAINERS}`; do
+	cname=`${SBINDIR}/cubename $c`
+
+	echo -n "Extracting rootfs $cname, with src $c....."
+
+	# untar it into temp, save it to record
+	tmpcontainer=`mktemp -d /tmp/hdcnt_dirXXXXX`
+	mergepatch=`get_prop_value_by_container $cname "mergepath"`
+
+	echo "$cname:$tmpcontainer:$mergepatch" >> ${CNRECORD}
+	mkdir -p $tmpcontainer/rootfs
+	tar --numeric-owner -xjf $c -C $tmpcontainer/rootfs
+
+	if [ $? != 0 ]; then
+		echo "failed!"
+		echo "Error: rootfs file extraction failed"
+		exit 1
+	fi
+	echo "succeeded"
+    done;
+
     for c in `strip_properties ${HDINSTALL_CONTAINERS}`; do
 	debugmsg ${DEBUG_INFO} "[INFO]: installing $c"
 
@@ -681,6 +707,14 @@ if [ -n "${HDINSTALL_CONTAINERS}" ]; then
 
 	rm ${TMPMNT}/tmp/$(basename $c)
     done
+
+    #cleanup temp files
+    for c in `strip_properties ${HDINSTALL_CONTAINERS}`; do
+        cname=`${SBINDIR}/cubename $c`
+        temp_dir=`cat ${CNRECORD}|awk -F ":" '{if ( $1=="'${cname}'" )print $2}'`
+        rm $temp_dir -r
+    done
+    rm ${CNRECORD}
 
     # install and modify services
     for c in `strip_properties ${HDINSTALL_CONTAINERS}`; do
